### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by josephbagnes** [jhipster/generator-jhipster-react-native#1722]
generator-jhipster: 8.3.0
generator-jhipster-react-native: 4.4.0

~/demo/mobile > rnhipster
node:internal/modules/cjs/loader:597
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './cli/utils' is not defined by "exports" in /Users/myself/.config/yarn/global/node_modules/generator-jhipster-react-native/node_modules/generator-jhipster/package.json
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:366:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:713:9)
    at resolveExports (node:internal/modules/cjs/loader:590:36)
    at Module._findPath (node:internal/modules/cjs/loader:664:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1126:27)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/myself/.config/yarn/global/node_modules/generator-jhipster-react-native/cli/rnhipster.js:21:20) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.20.1

**Comment by mraible** [comment]
I think the latest release of the React Native blueprint still requires Node 16.

**Comment by legendpeng** [comment]
I am seeing this as well, my nodejs is v20.14.0, which is the default version being used in jhipster 8.5.0. 

Ideally both this blueprint and jhipster  should use the same nodejs version?

any plan to fix this? or any known working workaround before it's fixed?

**Comment by legendpeng** [comment]
I also tried "jhipster --force jdl my_jdl_file --blueprints react-native" and got a similar stacktrace. both jhipster  and generator-jhipster-react-native are 8.5.0. 

`INFO! No custom commands found within blueprint: generator-jhipster-react-native at /usr/local/share/nvm/versions/node/v20.14.0/lib/node_modules/generator-jhipster-react-native
ERROR! ERROR! Package subpath './generators/app' is not defined by "exports" in /usr/local/share/nvm/versions/node/v20.14.0/lib/node_modules/generator-jhipster-react-native/node_modules/generator-jhipster/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './generators/app' is not defined by "exports" in /usr/local/share/nvm/versions/node/v20.14.0/lib/node_modules/generator-jhipster-react-native/node_modules/generator-jhipster/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:592:36)
    at Module._findPath (node:internal/modules/cjs/loader:669:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1131:27)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v20.14.0/lib/node_modules/generator-jhipster-react-native/generators/app/index.js:6:22)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
`

**Comment by mraible** [comment]
This will be fixed in the v4.5.0 release, which we're working on now.

**Comment by maheeptathgur-rb** [comment]
Any updates when is the newer version i.3 4.5.0 is going to get released?

**Comment by ikiddoi** [comment]
> Any updates when is the newer version i.3 4.5.0 is going to get released?

2026
